import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("hyperspace planners expose local, galactic, fuel-safety, and escape flows", async () => {
  const app = await readFile("renderer/src/app/App.tsx", "utf8");
  const planner = await readFile("renderer/src/features/hyperspace/HyperspacePlanner.tsx", "utf8");
  const computer = await readFile("renderer/src/features/hyperspace/NavigationComputer.tsx", "utf8");
  const transit = await readFile("renderer/src/features/hyperspace/HyperspaceTransit.tsx", "utf8");
  const field = await readFile("renderer/src/features/hyperspace/HyperspaceField.tsx", "utf8");
  const scraper = await readFile("mudlet/lotj_holocron_scraper.lua", "utf8");

  assert.match(app, /plot_hyperspace/);
  assert.match(app, /engage_hyperdrive/);
  assert.match(app, /escape_hyperspace/);
  assert.match(app, /HyperspaceTransit/);
  assert.match(app, /escapePlan\.triggerGalaxy/);
  assert.match(app, /needsCatalog/);
  assert.match(app, /needsPosition/);
  assert.match(app, /command: "navstat"/);
  assert.match(app, /refreshMissingNavigationData/);
  assert.match(app, /followupRadar: true/);
  assert.match(app, /setActiveRoute\(null\)/);
  assert.match(app, /\["hyperspace", "reentry"\]\.includes/);
  assert.match(app, /2_500/);
  assert.match(planner, /-50_000/);
  assert.match(planner, /ARM ESCAPE PLAN/);
  assert.doesNotMatch(planner, /mode === "galactic" && <div className=\{styles\.escape\}/);
  assert.match(planner, /reachableEscapeSystems/);
  assert.match(planner, /ROUTE BLOCKED/);
  assert.match(planner, /ACQUIRING RANGE DATA/);
  assert.match(planner, /ACQUIRING GALAXY CATALOG/);
  assert.match(planner, /catalogPending/);
  assert.match(planner, /occupiedSystem \? `YOU \/\/ \$\{occupiedSystem\.name\}` : "YOU"/);
  assert.match(planner, /system === occupiedSystem/);
  assert.match(planner, /styles\.galaxyPosition/);
  assert.match(planner, /normalized|Math\.cos/);
  assert.match(planner, /event\.shiftKey/);
  assert.match(planner, /setPointerCapture/);
  assert.match(computer, /INSUFFICIENT FUEL/);
  assert.match(computer, /ENGAGE ANYWAY/);
  assert.match(computer, /VERIFYING.*CLEARANCE/);
  assert.match(computer, /HYPERSPACE BLOCKED/);
  assert.match(computer, /disabled=\{!clearance\.allowed\}/);
  assert.match(transit, /Escape hyperspace/);
  assert.match(transit, /EMERGENCY HYPERDRIVE CUTOFF/);
  assert.match(transit, /HyperspaceField engaged/);
  assert.match(transit, /transition: "opacity 5s ease-out, filter 5s ease-out"/);
  assert.match(transit, /reentryFadeStarted \? 0 : 1/);
  assert.match(field, /edgeActivation/);
  assert.match(scraper, /calc stop/);
  assert.match(scraper, /"hyper off", false/);
  assert.match(scraper, /escape_hyperspace/);
  assert.match(scraper, /automation lease expired/i);
  assert.match(scraper, /Galaxy 1/);
  assert.match(scraper, /refresh_galaxy_catalog/);
  assert.match(scraper, /send, "planets", false/);
  assert.match(scraper, /galaxyCatalogRequestAt/);
  assert.match(scraper, /another telemetry refresh is active/);
  assert.match(scraper, /must be at a nav computer/);
  assert.match(app, /navigationRefreshBlocked/);
  assert.match(scraper, /capture\.followupRadar/);
  assert.match(scraper, /lotj\.galaxyMap\.systems/);
  assert.match(scraper, /Destination reached\. Initiating realspace reentry/);
  assert.match(scraper, /checkHyperspaceClearance/);
  assert.match(scraper, /MIN_HYPERSPACE_CLEARANCE = 500/);
  assert.match(await readFile("mudlet/lotj_holocron_parsers.lua", "utf8"), /\[%dsmh%s\]\+/);
});
